# Generated by Django 5.2.6 on 2025-09-05 09:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text="Enter the doctor's first name", max_length=64)),
                ('lastname', models.CharField(help_text="Enter the doctor's last name", max_length=64)),
                ('max_appointments_per_day', models.IntegerField(default=10, help_text='Max appointments a doctor can have per day')),
                ('email', models.EmailField(help_text="Enter the doctor's email address", max_length=128, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text="Select the doctor's gender", max_length=1)),
                ('specialization', models.CharField(choices=[('CARD', 'Cardiologist'), ('DERM', 'Dermatologist'), ('NEUR', 'Neurologist'), ('ORTH', 'Orthopedic'), ('PED', 'Pediatrician'), ('GEN', 'General Physician')], help_text="Select the doctor's specialization", max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text="Enter the patient's first name", max_length=64)),
                ('lastname', models.CharField(help_text="Enter the patient's last name", max_length=64)),
                ('email', models.EmailField(help_text="Enter the patient's email address", max_length=128, unique=True)),
                ('age', models.IntegerField(help_text="Enter the patient's age", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text="Select the patient's gender", max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDoctorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_mappings', to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mappings', to='hospital.patient')),
            ],
            options={
                'unique_together': {('patient', 'doctor', 'assigned_at')},
            },
        ),
    ]
